@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

Person(nutrixUser, "Nutrix User", "A Nutrix Platform user, typically  a nutrition professional.")


System_Boundary(c1, "NutriX Core") {

    Container(Backend_Application, "Backend Application", "Technology", "Optional Description")
    Container(Single_Page_App, "Single-Page App", "Technology", "Optional Description")

    ContainerDb(Database, "Database", "Microsoft SQL", "Optional Description")

}

System_Ext(Patient_Management_System, "Patient Management System")
System_Ext(FCT_System, "FCT System")


[nutrixUser] --> [Backend_Application]: Gives access to
[nutrixUser] --> [Single_Page_App]: Gives access to
[Backend_Application] --> [Database]: Gives access to
[Backend_Application] <- [Single_Page_App]: Gives access to
[Backend_Application] -> [Single_Page_App]: Gives access to
[nutrixUser] --> [FCT_System]: Gives access to
[nutrixUser] --> [Patient_Management_System]: Gives access to
[Single_Page_App] --> [FCT_System]: Gives access to
[Single_Page_App] -> [Patient_Management_System]: Gives access to

@enduml