@startuml Nutrix

skinparam sequenceMessageAlign center
title System Context Diagram for Nutrix Core System

caption System Context



agent nutrixUser[
    <b> Nutrix User 
    ----
    A Nutrix Platform user,
    typically  a nutrition
    professional.
]

component patientManagementSystem [
    <b> Patient Management System
    ----
    Stores all patient information
    and events
]

collections nutrixCore [
    <b> Nutrix Core System 
    ----
    Manages user information
    and acces to different Apps
    in the Nutrix Platform
]

component fctSystem [
    <b> FCT System
    ----
    System for viewing foods 
    with their nutricional value.
]


[nutrixUser] --> [patientManagementSystem]: Uses

[nutrixUser] <-- [nutrixCore]: Gives access to

[nutrixUser] --> [fctSystem]: Uses


[nutrixCore] --> [fctSystem]: Loads

[nutrixCore] --> [patientManagementSystem]: Loads


<style>



title {
    FontSize 18
    
}

caption{
    HorizontalAlignment center
}

rectangle {
    BackgroundColor DeepSkyBlue
    FontColor White
    TextAlignment center
}

agent {
    BackgroundColor Navy
    FontColor White
}

component{
    BackgroundColor Grey
    FontColor White
}

</style>


@enduml